### ISSUE TITLE
Highlighting uses specific dark/light CSS styles

### ISSUE THREAD

**Issue by TheGroundZero** [rhazdon/hugo-theme-hello-friend-ng#103]
Hi

I've noticed that certain highlights/stylings specifically refer to colours defined in the light or dark section (`assets/scss/_variables.scss`).

Is it possible to have a switch in these cases so that the highlights can be matched with the light or dark mode?

Example: **assets/scss/_list.scss**

``` css
  .post {
    &-title {
      font-size: 1rem;
      margin: 5px 0 5px 0;
    }

    &-year {
      padding-top: 6px;
      margin-right: 1.8em;
      font-size: 1.6em;
      @include dimmed;
      color: $dark-color-secondary; /* <-- this is what I'm referring to */

      @media #{$media-size-tablet} {
        margin: -6px 0 4px;
      }
    }
```
