### ISSUE TITLE
the customCSS/JS doesn't work well

### ISSUE THREAD

**Issue by iloook** [rhazdon/hugo-theme-hello-friend-ng#126]
I set config.toml as follows:
```toml
  customCSS = ["styles.css"]
  customJS  = ["scripts.js"]
```
When I open the homepage, it requests from the url like "http://localhost:1313/styles.css".
But After I open a post, the browser requsets a css (or js) from "http://localhost:1313/posts/year/month/postname/styles.css", which cannot be found.

So, I think the request path should be fixed in the static folder.
