### ISSUE TITLE
Css not working when deployed using Netlify

### ISSUE THREAD

**Issue by pablocrivella** [rhazdon/hugo-theme-hello-friend-ng#15]
### Description

The build succeeds now but the site look unstyled: https://pablocrivella.netlify.com

```toml
# netlify.toml

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.55.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
```
