### ISSUE TITLE
Issues with multilingualism

### ISSUE THREAD

**Issue by bsciretti** [rhazdon/hugo-theme-hello-friend-ng#164]
I'm trying to create a full multilingual website and, for some extent, it works, like in the string adaptation by language.

Btw, I found some problem:
1. The menu options are the same, in the main language. While clicking it doesn't return the correct language but the main language page
2. There's no menu choice for languages such in other themes

I don't know if it's a fault in the documentation or an entire thing to add, in the latter case I can make a pull request :)

**Comment by questoph** [comment]
ran into the same issue. solved this for me by using the language extension system in hugo and adding the menu info to each file for each language, e.g., 

filename with language extension: profile.en.md

url: "/en/profile/"
menu:
  main:
    name: "Profile"
    weight: 2

additionally, i moved the language switcher to the header menu.

**Comment by TheGroundZero** [comment]
This seems to work

```yaml
languages:
  en:
    languageName: 'English'
    menu:
      main:
        - identifier: about
          name: About Us
          url: /about/
          weight: 10
  nl:
    languageName: 'Nederlands'
    menu:
      main:
        - identifier: blog
          name: Over ons
          url: /over-ons/
          weight: 10
```

Double-check that `themes/hello-friend-ng/lay-outs/partials/menu.html` uses `relLangURL` (note the `Lang` part) and that you don't overwrite it in a custom menu template.

**Comment by exaucae** [comment]
I can't change the menu when switching language.

Here's the console output: 

````
>hugo serve -D
Error: "${ProjectPath}\config.toml:1:1": unmarshal failed: toml: table menu already exists
````

TOML config:

```toml

# config.toml

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight    = 1
    [menu]
      [[menu.main]]
            identifier = "home"
            name = "Home"
            url = "/"
            weight = 1

  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    title = 'techxaucae'
    weight    = 4
    [menu]
      [[menu.main]]
            identifier = "home-fr"
            name = "Acceuil"
            url = "/"
            weight = 1
```

Note: works fine when removing the menu from second language.
