### ISSUE TITLE
Cursor colour differs, relative path mistake?

### ISSUE THREAD

**Issue by TheGroundZero** [rhazdon/hugo-theme-hello-friend-ng#187]
Hi,

I noticed that while the cursor on the homepage nicely follows my preference set at `Site.Params.Logo.logoCursorColor`, it doesn't on other pages.

```toml
[params]
  [params.logo]
    logoText     = "nc sequr.be 1337"
    # Set to a valid CSS color to change the cursor in the logo.
    logoColor    = "#e68101"
```

Homepage

![image](https://user-images.githubusercontent.com/2406013/88412124-5a038980-cdd9-11ea-9c23-f1b8e9370b7a.png)

Blog page

![image](https://user-images.githubusercontent.com/2406013/88412154-6a1b6900-cdd9-11ea-9c04-a464c9094ed6.png)

Investigating this issue, I noticed the following error in my browser console when visiting the Blog page.
![image](https://user-images.githubusercontent.com/2406013/88411794-d5b10680-cdd8-11ea-9025-34b275a8614b.png)

My guess is that there's an issue with a relative path being used, since I have a the same error on the other pages (but notice the difference in path).
![image](https://user-images.githubusercontent.com/2406013/88411969-2163b000-cdd9-11ea-8937-b0c6a6965dbd.png)
