### ISSUE TITLE
rtl languages support

### ISSUE THREAD

**Issue by thantez** [rhazdon/hugo-theme-hello-friend-ng#189]
Hi. Can I use RTL languages like Arabic or Persian to write blogs? I tried in [this way](https://gohugo.io/content-management/multilingual/#configure-languages) and failed:
```toml
[languages]
  [languages.ar]
    languagedirection = "rtl"
    title = "مدونتي"
    weight = 2
  [languages.en]
    title = "My blog"
    weight = 1
```
And I named my files like this:
![image](https://user-images.githubusercontent.com/33148504/88489862-7277cd80-cfac-11ea-9da8-a8f1f8a97fb1.png)
Aren't you support RTL or It's my wrong?
