### ISSUE TITLE
change theme color 

### ISSUE THREAD

**Issue by p4r7h** [rhazdon/hugo-theme-hello-friend-ng#299]
is there any way to change theme color unless I can't change my theme color using scss files !!

**Comment by aghwotu** [comment]
Commenting here to ask for help for the same issue. I updated my styles successfully but it does not reflect when I deploy it to Netlify. What is the preferred way to change the styles? I created a stylesheet in the ```assets/css/style.css``` and included it in the ```baseof.html``` file. Please I would appreciate any help offered. 

 I am trying to change the styles for the light theme like so:

```css
[data-theme=light] #heading__title {
  color: #ffb531 !important;
}

[data-theme=light] body {
  background-color: #073642 !important;
  color: #fff !important;
}

[data-theme=light] .header {
  background-color: #002b36 !important;
}

[data-theme=light] .menu__inner {
  background-color: #002b36 !important;
}

[data-theme=light] .logo__cursor {
  background-color: #ffb531 !important;
}

[data-theme=light] a:hover {
  color: #ffb531 !important;
}
```
