### ISSUE TITLE
Menu not appearing anymore

### ISSUE THREAD

**Issue by ssulei7** [rhazdon/hugo-theme-hello-friend-ng#308]
Hello,

Love the theme, and have been using it for awhile now. However, my last deployment, I recently bumped into an issue where my menu items are not appearing on the header:

![image](https://user-images.githubusercontent.com/22037844/122628443-9e47ea00-d07b-11eb-8f78-126a4fbee61b.png)

My config.toml file looks as followed when it comes down to the menu items:
```toml
  # And you can even create generic menu
  [[menu.main]]
    identifier = "post"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"
```

I need help identifying what may be the underlying issue here.
