### ISSUE TITLE
Language menu gone

### ISSUE THREAD

**Issue by gibranlp** [rhazdon/hugo-theme-hello-friend-ng#334]
Hi, im trying to make a multilingual site, and everything works but suddenly the menu language disappeared, and i cant seem to get it back i have my ´´´enableGlobalLanguageMenu = true´´´ is there anything i can do to get back the menu? thanks

**Comment by HacDan** [comment]
This works for me with a pretty basic config.

@gibranlp Could your share your config file? Here's a partial of mine with it working

```toml
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  enableGlobalLanguageMenu = true
```
