### ISSUE TITLE
Cover image in single posts misalined

### ISSUE THREAD

**Issue by schneekluth** [rhazdon/hugo-theme-hello-friend-ng#366]
I am currently migrating my blog to this template and have encountered a strange issue with cover images for single posts. This issue only occurs on large screens. Mobile view is fine:

Sometimes cover images are placed centered but bigger than the textarea:
<img width="730" alt="grafik" src="https://user-images.githubusercontent.com/5740913/155722746-8e2348ed-19ac-43fc-8004-78238309fe33.png">

Sometimes cover images are placed to the left and the css for `border-round: 8px` isn't applied to the right side of the image:
<img width="696" alt="grafik" src="https://user-images.githubusercontent.com/5740913/155722948-df31d029-9571-4d80-95ee-fec68501730a.png">

Reason seems to be the CSS class "post-cover" and specifically the settings for `margin:` and `width:`. When I disable these settings everything seems to be correct: 
![Screenshot 2022-02-25 at 14 31 19](https://user-images.githubusercontent.com/5740913/155724133-44c70a9e-659b-4f0e-b849-3a83f783fee0.png)

Am I doing something wrong with the cover images? Here is an example how I integrate them:

```yaml
---
title: "Phoniebox - DIY NFC Audioplayer"
date: 2022-02-20T16:51:44+01:00
slug: "/phoniebox"
series: [diy]
categories: [raspberrypi]
tags: [nfc]
cover: "images/phoniebox/banner-phoniebox.png"
description: "Dieser Post behandelt den Bau einer sogenannten Phoniebox - einem NFC-Audioplayer mit kinderleichter Bedienung."
---
```
