### ISSUE TITLE
[Question] Change theme font

### ISSUE THREAD

**Issue by Mikerpen22** [rhazdon/hugo-theme-hello-friend-ng#376]
Hi! Is there a way to modify the font to something like Avenir? Thank you:)

**Comment by MayMeow** [comment]
I changed font on my page articles to **Input Mono Narrow**, it wasn't that hard, you can check:

You can edit `./themes/hello-friend/assets/scss/_font.scss` add there new font as follows

```scss
@font-face {
  font-family: 'Input Mono Narrow';
  font-style:  normal;
  font-display: auto;
  font-weight: 400;
  src: url("../fonts/InputMonoNarrow-Regular.woff2") format("woff2"),
       url("../fonts/InputMonoNarrow-Regular.woff") format("woff");
}
```

place your `woff` and `woff2` fonts in `./themes/hello-friend/staic/fonts`.

Then go to `./themes/hello-friend/assets/scss/_main.scss` and update body's font-family like bellow This will change font for whole page.

```scss
font-family: "Input Mono Narrow", -apple-system, BlinkMacSystemFont, "Roboto",
    "Segoe UI", Helvetica, Arial, sans-serif;
```

if you want to change font for articles update  `./themes/hello-friend/assets/scss/_single.scss` and update `&-content` directive as follows.

```scss
&-content {
    margin-top: 30px;
    font-family: "Input Mono Narrow", -apple-system, BlinkMacSystemFont, "Roboto",
    "Segoe UI", Helvetica, Arial, sans-serif;
  }
```

This is easiest way how to do it (I know about). If there is someone who know easier method post it here ;)
