### ISSUE TITLE
No Copyright information in my Russian HF-NG website

### ISSUE THREAD

**Issue by DragonSerW** [rhazdon/hugo-theme-hello-friend-ng#444]
``` toml
baseurl      = "https://splash.org.ru/"
title        = "Веб-каталог"
languageCode = "ru-RU"
theme        = "hello-friend-ng"
paginate     = 10

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Окунись в пучины!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Стартовый веб-сайт"
  keywords = "homepage, blog, стартовая, веб-страница, ПЭВМ, браузер"
  images = [""]

enableRobotsTXT = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.ru]
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Russian'
    title = 'Веб-каталог'
    weight = 1
    keywords = "старт, веб-страница, браузер, ПЭВМ, закладки, Интернет"
    copyright = '2023, Сергей Швайко, город Ейск <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Читать далее"
    [languages.ru.params]
      subtitle = 'Окунись в пучины!'
    [languages.ru.params.logo]
      logoText = "Вперед в Интернет!"
      logoHomeLink = "/"
    # or
    #
     path = "/img/1526478185.svg"
     alt = "Your example logo alt text"
      
    [[languages.ru.menu.main]]
    name = "Заглавная"
    pageref = "/"
    weight = 1
    [[languages.ru.menu.main]]
    name = "Записки"
    url = "post"
    weight = 2
    [[languages.ru.menu.main]]
    name = "Обо мне"
    pageref = "about"
    weight = 3
    [[languages.ru.menu.main]]
    name = "Связаться, как добраться"
    pageref = "contact-us"
    weight = 4
    [[languages.ru.menu.main]]
    name = "Поиск"
    pageref = "search"
    weight = 5
  [languages.en]
    contentDir = 'content/en'
    disabled = true
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Internet!'
    weight = 2
    keywords = "PC, macOS, Android, Start, web-page, Browser, Device"
    copyright = '2023, Sergei Shvaiko, Yeysk town. <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read further"
    [languages.en.params]
      subtitle = 'Start web-page for any browser and device'
    [languages.en.params.logo]
      logoText = "Internet!"
      logoHomeLink = "/"
    # or
    #
     path = "/img/1526478185.svg"
     alt = "Your example logo alt text"
    
    [[languages.en.menu.main]]
    name = "Home"
    pageref = "/"
    weight = 1
    [[languages.en.menu.main]]
    name = "Post"
    url = "post"
    weight = 2
    [[languages.en.menu.main]]
    name = "About me"
    pageref = "about"
    weight = 3
    [[languages.en.menu.main]]
    name = "Contact us"
    pageref = "contact-us"
    weight = 4
    [[languages.en.menu.main]]
    name = "Search"
    pageref = "search"
    weight = 5
    
```
