### ISSUE TITLE
Can't get posts to show

### ISSUE THREAD

**Issue by hcvazquez** [rhazdon/hugo-theme-hello-friend-ng#59]
Hey, I'm new to hugo and love your theme but i've tried to use the exampleSite  configuration and can't seem to get posts to show. I have hugo version = Hugo Static Site Generator v0.57.2/extended windows/amd64

**Comment by rivaquiroga** [comment]
Hi! I had the same problem. I found the solution here: https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/14. You need to comment out the taxonomies.

**Comment by rhazdon** [comment]
Thanks @rivaquiroga for the answer. :)
@hcvazques: Does it work?

**Comment by mattykay** [comment]
Can also confirm either removing or changing the template examples taxonomy as below works - appears this behavior changed as of Hugo >v0.57.1 (possibly [this commit](https://github.com/gohugoio/hugo/commit/9475f61a377fcf23f910cbfd4ddca59261326665)?)

From:
```toml
[taxonomies]
  tag      = "tags"
  category = ""
```

To: ([which is the default anyway](https://gohugo.io/content-management/taxonomies/#default-taxonomies))
```toml
[taxonomies]
  tag      = "tags"
  category = "categories"
```

Maybe it's worth removing it from the example? - I can raise a PR if so.
